---
galaxy_info:
  author: Lazio
  description: MongoDB Sharded Cluster Installation
  company: -
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: EL
      versions:
        - 8
        - 9

dependencies: []
