---
- name: Create arbiter data directory
  file:
    path: "{{ base_data_dir }}/arbiter"
    state: directory
    owner: mongod
    group: mongod
    mode: '0755'

- name: Create log directory
  file:
    path: "{{ log_dir }}"
    state: directory
    owner: mongod
    group: mongod
    mode: '0755'

- name: Create config directory
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy arbiter config
  template:
    src: mongodb_arbiter.conf.j2
    dest: "{{ config_dir }}/mongodb_arbiter.conf"
    owner: mongod
    group: mongod
    mode: '0644'
  notify: restart mongodb-arbiter

- name: Create systemd service
  template:
    src: mongodb-arbiter.service.j2
    dest: /etc/systemd/system/mongodb-arbiter.service
    owner: root
    group: root
    mode: '0644'
  notify: restart mongodb-arbiter

- name: Enable and start arbiter service
  systemd:
    name: mongodb-arbiter
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for arbiter port
  wait_for:
    port: "{{ arbiter_port }}"
    delay: 5
    timeout: 60
