---
- name: Create log directory
  file:
    path: "{{ log_dir }}"
    state: directory
    owner: mongod
    group: mongod
    mode: '0755'

- name: Create config directory
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy mongos config
  template:
    src: mongos.conf.j2
    dest: "{{ config_dir }}/mongos.conf"
    owner: mongod
    group: mongod
    mode: '0644'
  notify: restart mongos

- name: Create systemd service
  template:
    src: mongos.service.j2
    dest: /etc/systemd/system/mongos.service
    owner: root
    group: root
    mode: '0644'
  notify: restart mongos

- name: Enable and start mongos service
  systemd:
    name: mongos
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for mongos port
  wait_for:
    port: "{{ mongos_port }}"
    delay: 5
    timeout: 60
